Video Transcription Docx Generation
Transcribe-doc.js uses the Docx library to create a word document from the created transcript. Added changes to the package.json including updating serverless to v3. Errors with TranscribeDoc function (TypeError: TranscribeDoc is not a function). Need to review.